Resolves #690, adds support for Node.js 4.2.2 LTS
I had to update some dependencies due to deprecated functions.

There is an outstanding issue with a dependency on bson which gives the following warning:
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version